### ISSUE TITLE
Prioritise characters closest to point.

### ISSUE THREAD

**Issue by Wilfred** [waymondo/ace-jump-zap#7]
If I have the following file, where `|` is point:

```
<!DOCTYPE html>
<html>
    <head>
        <title>
        </title>
        <style type="text/css">
        </style>
    </head>
    <body>
        <p>foo| bar</p>
    </body>
</html>
```

If I call `M-x ace-jump-zap-up-to-char <RET> < <RET>`, I end up with:

![zap_cropped](https://cloud.githubusercontent.com/assets/70800/5342383/8c6b1c32-7ef5-11e4-9dae-62f25743a0ef.png)

This is less useful -- it's rare that I would want to zap all the way to the beginning. This is particularly awkward when I'm zapping up to a common character, such as a space.

Could ace-jump-zap ensure that the characters closest to point are prioritised? I'd like something like this:

```
Bbody>
  Ap>foo| bara/p>
b/body>
```

so the closest characters after point are assigned `a`, `b` and so on.

**Comment by waymondo** [comment]
I hear what you're saying, but I feel it would be too confusing to limit ensurable single zaps from a range like `a` through `f`. It could be "learnable" but I think its confusing.

What if there was a custom variable like `ajz/52-character-limit` which would ensure a single zap, since `a`-`z` and `A`-`Z` are only used once? Combined with `ajz/forward-only` that sounds like it might work for you.

**Comment by Wilfred** [comment]
Yep, something like that (perhaps `ajz/single-keypress` or `ajz/single-zap` so you could expand [a-zA-z] to [a-zA-Z0-9] if you wanted?) would be wonderful.

**Comment by waymondo** [comment]
it took me a while but i finally figured out a way to implement this. check out the latest commit and let me know if that works for you. i definitely think its an improvement.

**Comment by Wilfred** [comment]
That is just perfect. Thank you :)
